Timer: Do actions shutdown within with_fake_time
Otherwise it can happen that Time.now is called while the method is
re-assigned to the original implementation leading to a:

  NoMethodError: undefined method `now' for Time:Class